image_root: '/home/adityasv/webqa/WebQA/WebQA_data_first_release/imgs.tsv'
train_val_root: '/home/adityasv/webqa/WebQA/WebQA_data_first_release'
test_data_root: '/home/adityasv/webqa/WebQA/WebQA_data_first_release/WebQA_test.json'
dataset: 'webqa'
max_question_length: 30
max_caption_length: 30
max_passage_length: 128
prompt: ''

# set pretrained as a file path or an url
# pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_retrieval_coco.pth'
pretrained: '/home/adityasv/webqa/BLIP/checkpoints/model_base.pth'
use_image_grounded_text_encoder: False

sim_matrix_prefix: 'base'

# size of vit model; base or large
vit: 'base'
batch_size_train: 4
batch_size_test: 64
vit_grad_ckpt: True
vit_ckpt_layer: 4
init_lr: 1e-5

# vit: 'large'
# batch_size_train: 16
# batch_size_test: 32
# vit_grad_ckpt: True
# vit_ckpt_layer: 12
# init_lr: 5e-6

image_size: 384
queue_size: 57600
alpha: 0.4
k_test: 256
negative_all_rank: False
# negative_all_rank: True

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 6

